[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "pnpm run build"
  publish = ".next"
  base = "todo-frontend"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"
