services:
  todo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend-app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      # ASP.NET Core environment
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      # Aiven MySQL connection string
      - ConnectionStrings__DefaultConnection=Server=${AIVEN_HOST};Port=${AIVEN_PORT};Database=${AIVEN_DB};User=${AIVEN_USER};Password=${AIVEN_PASSWORD};
      # Optional: Firebase path (used inside app)
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-adminsdk.json
    volumes:
      # Mount Firebase service account as read-only
      - ./firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
    networks:
      - todo-network
    restart: unless-stopped

  todo-frontend:
    build:
      context: ../todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend-app
    ports:
      - "3000:3000"
    environment:
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - todo-network
    restart: unless-stopped

networks:
  todo-network:
    driver: bridge
