name: Full Stack CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ToDo_backend
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./ToDo_backend
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      working-directory: ./ToDo_backend

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
      working-directory: ./ToDo_backend

    - name: Upload Backend Artifact
      uses: actions/upload-artifact@v4
      with:
        name: todo-backend
        path: ./ToDo_backend/publish

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install
      working-directory: ./todo-frontend
      
    - name: Lint
      run: pnpm lint
      working-directory: ./todo-frontend
      
    - name: Build
      run: pnpm build
      working-directory: ./todo-frontend
      
    - name: Upload Frontend Artifact
      uses: actions/upload-artifact@v4
      with:
        name: todo-frontend
        path: ./todo-frontend/.next

  